from sqlalchemy import text

from app.common import now
from app.database import SessionLocal
from app.security import hash_password

STUDENTS = [
    (
        "2026001",
        "林夏",
        "2026级",
        "FEMALE",
        24,
        26,
        20,
        23,
        ["早起", "午休"],
        "STRICT",
        ["开朗", "直接"],
        ["坦诚", "有边界感"],
        ["摄影", "音乐"],
        ["羽毛球"],
        "OCCASIONAL",
        "CONDITIONAL",
        "MIND",
        "我整理东西时容易过度追求分类。",
        "希望一起把宿舍住成舒服、彼此尊重的小空间。",
    ),
    (
        "2026002",
        "陈遇",
        "2026级",
        "MALE",
        25,
        27,
        19,
        22,
        ["晚睡"],
        "NORMAL",
        ["安静", "随和"],
        ["好沟通", "稳定"],
        ["电影", "桌游"],
        ["跑步"],
        "FREQUENT",
        "TOLERATE",
        "MIND",
        "有时戴着耳机就听不到别人叫我。",
        "游戏会戴耳机，也愿意提前约定安静时间。",
    ),
    (
        "2026003",
        "苏晴",
        "2025级",
        "FEMALE",
        24,
        25,
        21,
        24,
        ["早起"],
        "STRICT",
        ["自律", "慢热"],
        ["整洁", "守时"],
        ["阅读", "烘焙"],
        ["游泳"],
        "RARELY",
        "MIND",
        "MIND",
        "刚认识时话不多，需要一点熟悉时间。",
        "希望晚上十一点后尽量安静。",
    ),
    (
        "2026004",
        "周屿",
        "2025级",
        "MALE",
        23,
        26,
        18,
        22,
        ["晚睡", "午休"],
        "RELAXED",
        ["外向", "幽默"],
        ["包容", "直爽"],
        ["篮球", "电竞"],
        ["篮球"],
        "FREQUENT",
        "TOLERATE",
        "CONDITIONAL",
        "偶尔会忘记把衣服及时收进柜子。",
        "喜欢热闹，但重要时间会尊重大家的安排。",
    ),
    (
        "2026005",
        "沈知行",
        "2026级",
        "MALE",
        26,
        28,
        20,
        24,
        ["早起", "午休"],
        "NORMAL",
        ["理性", "温和"],
        ["讲道理", "可靠"],
        ["编程", "科幻"],
        ["骑行"],
        "OCCASIONAL",
        "CONDITIONAL",
        "MIND",
        "做事情投入时会忘记时间。",
        "可以一起学习，也能各自安静做自己的事。",
    ),
    (
        "2026006",
        "江晚",
        "2026级",
        "FEMALE",
        24,
        27,
        20,
        23,
        ["晚睡"],
        "NORMAL",
        ["细腻", "独立"],
        ["尊重隐私", "友善"],
        ["绘画", "音乐"],
        ["瑜伽"],
        "RARELY",
        "MIND",
        "MIND",
        "对突然的噪音比较敏感。",
        "期待有边界感，也愿意互相照顾的室友关系。",
    ),
    (
        "2026007",
        "许舟",
        "2026级",
        "MALE",
        24,
        26,
        19,
        22,
        ["早起"],
        "STRICT",
        ["自律", "直接"],
        ["整洁", "好沟通"],
        ["吉他", "历史"],
        ["足球"],
        "OCCASIONAL",
        "CONDITIONAL",
        "MIND",
        "周末有时起得特别早。",
        "希望一起维护安静整洁的宿舍。",
    ),
    (
        "2026008",
        "唐宁",
        "2025级",
        "FEMALE",
        25,
        27,
        20,
        24,
        ["晚睡", "午休"],
        "NORMAL",
        ["随和", "开朗"],
        ["友善", "有边界感"],
        ["舞蹈", "电影"],
        ["网球"],
        "RARELY",
        "MIND",
        "MIND",
        "偶尔会把快递盒放到第二天再收。",
        "愿意提前沟通作息和卫生安排。",
    ),
    (
        "2026009",
        "顾言",
        "2025级",
        "MALE",
        23,
        25,
        18,
        21,
        ["晚睡"],
        "RELAXED",
        ["安静", "独立"],
        ["尊重隐私", "包容"],
        ["模型", "音乐"],
        ["乒乓球"],
        "FREQUENT",
        "TOLERATE",
        "MIND",
        "专注时不太主动聊天。",
        "打游戏会戴耳机，不影响他人休息。",
    ),
    (
        "2026010",
        "叶澜",
        "2026级",
        "FEMALE",
        24,
        26,
        21,
        24,
        ["早起", "午休"],
        "STRICT",
        ["细腻", "自律"],
        ["守时", "坦诚"],
        ["手账", "阅读"],
        ["慢跑"],
        "RARELY",
        "MIND",
        "MIND",
        "对桌面杂物比较敏感。",
        "希望生活节奏稳定，公共区域保持整洁。",
    ),
    (
        "2026011",
        "陆川",
        "2026级",
        "MALE",
        25,
        28,
        20,
        23,
        ["晚睡"],
        "NORMAL",
        ["外向", "随和"],
        ["直爽", "好沟通"],
        ["旅行", "摄影"],
        ["排球"],
        "OCCASIONAL",
        "CONDITIONAL",
        "CONDITIONAL",
        "偶尔说话声音会有点大。",
        "接受不同作息，重要事情及时沟通。",
    ),
    (
        "2026012",
        "温然",
        "2025级",
        "FEMALE",
        24,
        25,
        20,
        22,
        ["早起"],
        "NORMAL",
        ["温和", "慢热"],
        ["包容", "尊重隐私"],
        ["钢琴", "展览"],
        ["羽毛球"],
        "RARELY",
        "MIND",
        "MIND",
        "刚认识时比较拘谨。",
        "期待安静、有边界感又互相照顾的宿舍。",
    ),
]


def main() -> None:
    timestamp = now()
    admin_password = hash_password("Admin123!")
    with SessionLocal.begin() as db:
        db.execute(
            text("""INSERT INTO grades(code,name,status,created_at,updated_at) VALUES
              ('2026级','2026级','ACTIVE',:now,:now),('2025级','2025级','ACTIVE',:now,:now)"""),
            {"now": timestamp},
        )
        admin_id = db.execute(
            text("""INSERT INTO users(login_identifier,password_hash,password_salt,role,account_type,
              authorization_version,must_change_password,name,grade,gender,major,status,created_at,updated_at)
              VALUES('admin',:hash,:salt,'ADMIN','SUPER_ADMIN',1,0,'系统管理员','-','UNSPECIFIED','',
              'ACTIVE',:now,:now) RETURNING id"""),
            {"hash": admin_password.hash, "salt": admin_password.salt, "now": timestamp},
        ).scalar_one()
        round_id = db.execute(
            text("""INSERT INTO dormitory_selection_rounds(code,name,description,status,created_by,opened_at,
              created_at,updated_at) VALUES('LEGACY_INITIAL','默认选宿舍轮次','Python 测试种子','OPEN',:admin,
              :now,:now,:now) RETURNING id"""),
            {"admin": admin_id, "now": timestamp},
        ).scalar_one()
        grade_ids = dict(db.execute(text("SELECT code,id FROM grades")).all())

        for index, student in enumerate(STUDENTS, start=1):
            (
                login,
                name,
                grade,
                gender,
                summer_min,
                summer_max,
                winter_min,
                winter_max,
                sleep,
                cleanliness,
                personality,
                expected,
                hobbies,
                sports,
                gaming,
                keyboard,
                media,
                weakness,
                note,
            ) = student
            password = hash_password("Student123!")
            major = ("计算机科学与技术", "视觉传达设计", "工商管理")[(index - 1) % 3]
            user_id = db.execute(
                text("""INSERT INTO users(login_identifier,password_hash,password_salt,role,account_type,
                  authorization_version,must_change_password,name,grade,grade_id,gender,major,status,imported_by,
                  created_at,updated_at) VALUES(:login,:hash,:salt,'STUDENT','USER',1,0,:name,:grade,:grade_id,
                  :gender,:major,'ACTIVE',:admin,:now,:now) RETURNING id"""),
                {
                    "login": login,
                    "hash": password.hash,
                    "salt": password.salt,
                    "name": name,
                    "grade": grade,
                    "grade_id": grade_ids[grade],
                    "gender": gender,
                    "major": major,
                    "admin": admin_id,
                    "now": timestamp,
                },
            ).scalar_one()
            gaming_label = {"FREQUENT": "经常", "OCCASIONAL": "偶尔", "RARELY": "很少"}[gaming]
            db.execute(
                text("""INSERT INTO roommate_cards(user_id,avatar_url,school,campus,department,origin_province,
                  origin_city,clothing_size,summer_temp_min,summer_temp_max,winter_temp_min,winter_temp_max,
                  wake_up_time,sleep_time,nap_habit,personal_cleanliness,roommate_cleanliness,
                  common_space_maintenance,unacceptable_hygiene,one_sentence_intro,personality_text,
                  roommate_personality_text,interests_text,gaming_self,gaming_roommate,keyboard_noise_text,
                  media_noise_text,self_acknowledged_shortcoming,additional_note,status,published_at,created_at,updated_at)
                  VALUES(:user,:avatar,'明德大学',:campus,:major,:province,:city,:size,:summer_min,:summer_max,
                  :winter_min,:winter_max,:wake,:sleep_time,:nap,:personal_clean,:roommate_clean,'NEGOTIABLE',
                  '长期不倒垃圾、在宿舍吸烟',:intro,:personality,:expected,:interests,:gaming_self,
                  '可以打游戏，休息时请戴耳机',:keyboard_noise,:media_noise,:weakness,:note,'PUBLISHED',
                  :now,:now,:now)"""),
                {
                    "user": user_id,
                    "avatar": f"/assets/avatar-{index}.png",
                    "campus": "南校区" if index % 2 == 0 else "北校区",
                    "major": major,
                    "province": ("浙江", "江苏", "上海", "安徽")[(index - 1) % 4],
                    "city": ("杭州", "南京", "上海", "合肥")[(index - 1) % 4],
                    "size": ("M", "L", "XL")[(index - 1) % 3],
                    "summer_min": summer_min,
                    "summer_max": summer_max,
                    "winter_min": winter_min,
                    "winter_max": winter_max,
                    "wake": "7:00 左右" if "早起" in sleep else "8:30 左右",
                    "sleep_time": "0:30 左右" if "晚睡" in sleep else "23:30 左右",
                    "nap": "有午休习惯，通常 30 分钟" if "午休" in sleep else "一般不午休",
                    "personal_clean": "STRICT"
                    if cleanliness == "STRICT"
                    else "TIDY"
                    if cleanliness == "NORMAL"
                    else "BASIC",
                    "roommate_clean": "STRICT" if cleanliness == "STRICT" else "BASIC",
                    "intro": f"我是一个{'、'.join(personality)}，喜欢{'、'.join([*hobbies, *sports])}的人。",
                    "personality": "、".join(personality),
                    "expected": "、".join(expected),
                    "interests": "、".join([*hobbies, *sports]),
                    "gaming_self": f"{gaming_label}打游戏，会注意休息时间",
                    "keyboard_noise": "休息时介意连续点击声，其他时间可以接受"
                    if keyboard == "MIND"
                    else "正常使用可以接受",
                    "media_noise": "介意外放，请使用耳机" if media == "MIND" else "短时间可以，休息时请使用耳机",
                    "weakness": weakness,
                    "note": note,
                    "now": timestamp,
                },
            )
            db.execute(
                text("""INSERT INTO dormitory_round_participants(round_id,user_id,added_by,created_at)
                  VALUES(:round,:user,:admin,:now)"""),
                {"round": round_id, "user": user_id, "admin": admin_id, "now": timestamp},
            )

        for index in range(1, 11):
            password = hash_password("Student123!")
            user_id = db.execute(
                text("""INSERT INTO users(login_identifier,password_hash,password_salt,role,account_type,
                  authorization_version,must_change_password,name,grade,grade_id,gender,major,status,imported_by,
                  created_at,updated_at) VALUES(:login,:hash,:salt,'STUDENT','USER',1,0,:name,'2026级',:grade,
                  'FEMALE','计算机科学与技术','ACTIVE',:admin,:created,:created) RETURNING id"""),
                {
                    "login": f"browser-page-{index:02d}",
                    "hash": password.hash,
                    "salt": password.salt,
                    "name": f"分页同学{index:02d}",
                    "grade": grade_ids["2026级"],
                    "admin": admin_id,
                    "created": "2020-01-01T00:00:00.000Z",
                },
            ).scalar_one()
            db.execute(
                text("""INSERT INTO roommate_cards(user_id,avatar_url,origin_city,one_sentence_intro,status,
                  published_at,created_at,updated_at) VALUES(:user,'/assets/avatar-1.png','深圳',
                  '用于验证查看更多功能','PUBLISHED',:created,:created,:created)"""),
                {"user": user_id, "created": "2020-01-01T00:00:00.000Z"},
            )


if __name__ == "__main__":
    main()
