const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright-core');

const browserExecutable = process.env.BROWSER_EXECUTABLE
  || (process.platform === 'win32'
    ? String.raw`C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`
    : '/usr/bin/google-chrome');
const baseUrl = process.env.APP_URL || 'http://127.0.0.1:4173';
const outputDir = path.join(__dirname, '..', 'artifacts');
fs.mkdirSync(outputDir, { recursive: true });

async function login(page, identifier, password) {
  await page.goto(`${baseUrl}/roommates`, { waitUntil: 'networkidle' });
  await page.waitForSelector('#login-form');
  assert.equal(new URL(page.url()).pathname, '/login');
  assert.equal(new URL(page.url()).searchParams.get('next'), '/roommates');
  assert.equal(await page.locator('.modal').count(), 0);
  assert.equal(await page.locator('[data-demo-id]').count(), 0);
  await page.locator('#login-id').fill(identifier);
  await page.locator('#login-password').fill(password);
  await page.locator('#login-form button[type="submit"]').click();
  await page.waitForSelector('.app-shell');
}

let browser;

(async () => {
  browser = await chromium.launch({ executablePath: browserExecutable, headless: true });
  const errors = [];

  const timezonePage = await browser.newPage({
    viewport: { width: 800, height: 600 },
    timezoneId: 'America/Los_Angeles',
  });
  await timezonePage.goto(`${baseUrl}/login`, { waitUntil: 'networkidle' });
  const activityTimezone = await timezonePage.evaluate(() => ({
    date: activityDateKey('2026-09-16T16:30:00.000Z'),
    time: activityTimeLabel({
      isAllDay: false,
      startAt: '2026-09-16T16:30:00.000Z',
      endAt: '2026-09-16T17:30:00.000Z',
    }),
    timestamp: activityTimestamp('2026-09-17T00:30'),
    weekTop: (() => {
      state.activityDate = activityDateFromKey('2026-09-17');
      const host = document.createElement('div');
      host.innerHTML = activityWeekMarkup({
        rangeStart: '2026-09-14',
        activities: [{ id: 1, title: '时区检查', startAt: '2026-09-17T06:00:00.000Z', endAt: '2026-09-17T07:00:00.000Z', isAllDay: false, importance: 3 }],
      });
      return host.querySelector('.activity-week-cluster').style.top;
    })(),
  }));
  assert.deepEqual(activityTimezone, {
    date: '2026-09-17',
    time: '00:30–01:30',
    timestamp: '2026-09-16T16:30:00.000Z',
    weekTop: '260px',
  });
  await timezonePage.close();

  const desktop = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  desktop.on('console', (message) => { if (message.type() === 'error' && !message.text().startsWith('Failed to load resource')) errors.push(`desktop console: ${message.text()}`); });
  desktop.on('pageerror', (error) => errors.push(`desktop page: ${error.message}`));
  const anonymousSessionResponse = desktop.waitForResponse((response) => response.url() === `${baseUrl}/api/me`);
  await desktop.goto(baseUrl, { waitUntil: 'domcontentloaded' });
  assert.equal((await anonymousSessionResponse).status(), 401);
  await desktop.waitForSelector('.public-shell');
  assert.equal(await desktop.locator('.site-logo img').getAttribute('src'), '/assets/logo/透明底白色字.png');
  assert.ok(await desktop.locator('.site-logo img').evaluate((image) => image.complete && image.naturalWidth > 0));
  assert.equal(await desktop.locator('.markdown-article h1').count(), 1);
  assert.equal(await desktop.locator('#site-login').count(), 1);
  assert.equal(await desktop.locator('#site-login').textContent(), '登录');
  assert.equal(await desktop.locator('#site-login').getAttribute('href'), '/login');
  const repositoryLink = desktop.locator('.site-footer a');
  assert.equal(await repositoryLink.getAttribute('href'), 'https://github.com/Crab-Dave/OpenShude');
  assert.equal(await repositoryLink.getAttribute('target'), '_blank');
  assert.equal(await repositoryLink.getAttribute('rel'), 'noopener noreferrer');
  assert.equal(await repositoryLink.locator('svg').count(), 1);
  assert.match(await repositoryLink.textContent(), /Crab-Dave\/OpenShude/);
  assert.equal(await desktop.locator('.site-nav a[href="/shudong"]').count(), 1);
  assert.equal(await desktop.locator('.site-nav a[href="/sude"]').count(), 1);
  assert.equal(await desktop.locator('.site-nav a[href="/activities"]').count(), 1);
  await desktop.screenshot({ path: path.join(outputDir, 'homepage-desktop.png'), fullPage: true });
  await desktop.locator('.site-nav a[href="/sude"]').click();
  await desktop.waitForSelector('#login-form');
  assert.equal(new URL(desktop.url()).pathname, '/login');
  assert.equal(new URL(desktop.url()).searchParams.get('next'), '/sude');
  await desktop.locator('#login-home').click();
  await desktop.waitForSelector('.public-shell');
  await desktop.locator('.site-nav a[href="/shudong"]').click();
  await desktop.waitForSelector('#login-form');
  assert.equal(new URL(desktop.url()).pathname, '/login');
  assert.equal(new URL(desktop.url()).searchParams.get('next'), '/shudong');
  await desktop.locator('#login-home').click();
  await desktop.waitForSelector('.public-shell');
  await desktop.locator('#site-login').click();
  await desktop.waitForSelector('.login-shell');
  assert.equal(new URL(desktop.url()).pathname, '/login');
  assert.equal(await desktop.locator('.modal').count(), 0);
  await desktop.screenshot({ path: path.join(outputDir, 'login-desktop.png'), fullPage: true });
  await desktop.locator('#login-home').click();
  await desktop.waitForSelector('.public-shell');

  await login(desktop, '2026001', 'Student123!');
  await desktop.waitForSelector('.roommate-card');
  const avatarRecovery = await desktop.evaluate(() => {
    const host = document.createElement('div');
    host.innerHTML = avatar(`/api/avatars/${'0'.repeat(64)}.png`, '头像恢复测试');
    document.body.append(host);
    const image = host.querySelector('img');
    const initialSource = image.getAttribute('src');
    image.dispatchEvent(new Event('error'));
    const fallbackSource = image.getAttribute('src');
    image.dispatchEvent(new Event('error'));
    const repeatedFallbackSource = image.getAttribute('src');
    host.remove();
    return { initialSource, fallbackSource, repeatedFallbackSource };
  });
  assert.match(avatarRecovery.initialSource, /^\/api\/avatars\/[0-9a-f]{64}\.png\?v=20260826$/);
  assert.equal(avatarRecovery.fallbackSource, '/assets/avatar-1.png');
  assert.equal(avatarRecovery.repeatedFallbackSource, '/assets/avatar-1.png');
  const authenticationCookies = await desktop.context().cookies(`${baseUrl}/api/auth/refresh`);
  const accessCookie = authenticationCookies.find((cookie) => cookie.name === 'access_token');
  const refreshCookie = authenticationCookies.find((cookie) => cookie.name === 'refresh_token');
  const csrfCookie = authenticationCookies.find((cookie) => cookie.name === 'csrf_token');
  assert.equal(accessCookie.httpOnly, true);
  assert.equal(accessCookie.sameSite, 'Lax');
  assert.equal(refreshCookie.httpOnly, true);
  assert.equal(refreshCookie.sameSite, 'Strict');
  assert.equal(csrfCookie.httpOnly, false);
  let refreshRequests = 0;
  const trackRefresh = (request) => {
    if (request.url() === `${baseUrl}/api/auth/refresh`) refreshRequests += 1;
  };
  desktop.on('request', trackRefresh);
  await desktop.context().clearCookies({ name: 'access_token' });
  const refreshedUsers = await desktop.evaluate(() => Promise.all([api('/api/me'), api('/api/me')]));
  desktop.off('request', trackRefresh);
  assert.equal(refreshRequests, 1);
  assert.equal(refreshedUsers.every((session) => session.user.name === '林夏'), true);
  assert.equal(
    (await desktop.context().cookies(`${baseUrl}/api/me`)).some((cookie) => cookie.name === 'access_token'),
    true,
  );
  const loggedInSessionResponse = desktop.waitForResponse((response) => response.url() === `${baseUrl}/api/me`);
  await desktop.locator('#home-btn').click();
  assert.equal((await loggedInSessionResponse).status(), 200);
  await desktop.waitForSelector('.public-shell');
  assert.equal(await desktop.locator('#site-login').textContent(), '进入系统');
  assert.equal(await desktop.locator('#site-login').getAttribute('href'), '/roommates');
  await desktop.locator('.site-nav a[href="/shudong"]').click();
  await desktop.waitForSelector('.treehole-card');
  assert.equal(new URL(desktop.url()).pathname, '/shudong');
  assert.equal(await desktop.locator('.sidebar-brand strong').textContent(), '树洞道理');
  assert.equal(await desktop.locator('.treehole-card').count(), 15);
  assert.equal(await desktop.locator('#load-more-treehole').count(), 1);
  assert.doesNotMatch(await desktop.locator('#treehole-public-list').textContent(), /林夏|系统管理员|2026001/);
  await desktop.locator('.treehole-card').first().click();
  await desktop.waitForSelector('.treehole-detail');
  assert.equal(await desktop.locator('.treehole-body h2', { hasText: '慢慢适应' }).count(), 1);
  assert.equal(await desktop.locator('.treehole-body strong', { hasText: '先照顾好自己' }).count(), 1);
  assert.equal(await desktop.locator('.treehole-body blockquote').count(), 1);
  assert.doesNotMatch(await desktop.locator('.treehole-body').textContent(), /\*\*|^##/);
  assert.equal(await desktop.locator('.official-label', { hasText: '管理员' }).count(), 1);
  assert.doesNotMatch(await desktop.locator('.modal').textContent(), /林夏|系统管理员|2026001/);
  await desktop.locator('.modal [data-close]').click();
  await desktop.locator('[data-view="treehole-mine"]').first().click();
  await desktop.waitForSelector('.treehole-mine-item');
  assert.equal(await desktop.locator('#create-treehole-post').count(), 1);
  assert.match(await desktop.locator('.treehole-mine-list').textContent(), /等待回复/);
  assert.match(await desktop.locator('.treehole-mine-list').textContent(), /可公开/);
  await desktop.locator('#create-treehole-post').click();
  await desktop.locator('#treehole-editor-content').fill('## 预览标题\n\n这里有 **重点内容**。');
  await desktop.locator('[data-treehole-preview]').click();
  await desktop.waitForSelector('.treehole-markdown-preview h2');
  assert.equal(await desktop.locator('.treehole-markdown-preview strong', { hasText: '重点内容' }).count(), 1);
  await desktop.locator('[data-treehole-preview]').click();
  assert.equal(await desktop.locator('#treehole-editor-content').isVisible(), true);
  await desktop.locator('[data-cancel]').click();
  await desktop.screenshot({ path: path.join(outputDir, 'treehole-desktop.png'), fullPage: true });
  await desktop.locator('#official-dormitory-system-btn').click();
  await desktop.waitForSelector('#official-dormitory-selector');
  assert.equal(new URL(desktop.url()).pathname, '/sude');
  assert.equal(await desktop.locator('.sidebar-brand strong').textContent(), '宿得道理');
  assert.equal(await desktop.locator('#official-dormitory-selector option').count(), 2);
  const primaryDormitoryId = await desktop.locator('#official-dormitory-selector option', { hasText: '星光小屋' }).getAttribute('value');
  await desktop.locator('#official-dormitory-selector').selectOption(primaryDormitoryId);
  await desktop.waitForFunction(() => document.querySelector('.official-dormitory-hero')?.textContent.includes('星光小屋'));
  assert.match(await desktop.locator('.official-member-card.leader').textContent(), /宿舍长/);
  assert.match(await desktop.locator('.official-member-grid').textContent(), /林夏/);
  assert.match(await desktop.locator('.official-content-summary').first().textContent(), /我们的宿舍.*爱摄影也爱生活/);
  assert.equal(await desktop.locator('.official-content-card h2', { hasText: '我们的宿舍' }).count(), 0);
  await desktop.locator('[data-official-content="宿舍简介"]').click();
  await desktop.waitForSelector('.modal .treehole-body h2');
  assert.equal(await desktop.locator('.modal .treehole-body strong', { hasText: '爱摄影也爱生活' }).count(), 1);
  await desktop.locator('.modal [data-close]').click();
  assert.equal(await desktop.locator('.official-garden button').isDisabled(), true);
  assert.match(await desktop.locator('.official-garden').textContent(), /建设中/);
  await desktop.locator('[data-edit-official-dormitory]').click();
  await desktop.locator('[data-preview-official="description"]').click();
  await desktop.waitForSelector('[data-official-preview-area="description"] h2');
  assert.equal(await desktop.locator('[data-official-preview-area="description"] strong').count(), 1);
  await desktop.locator('#official-dormitory-editor [data-cancel]').click();
  await desktop.locator('[data-view="official-visit"]').first().click();
  await desktop.waitForSelector('.official-visit-card');
  assert.equal(await desktop.locator('.official-visit-card').count(), 15);
  assert.equal(await desktop.locator('[data-load-more-official]').count(), 1);
  await desktop.locator('[data-load-more-official]').click();
  await desktop.waitForFunction(() => document.querySelectorAll('.official-visit-card').length === 18);
  assert.equal(await desktop.locator('[data-load-more-official]').count(), 0);
  await desktop.locator('#official-dormitory-search input').fill('星光小屋');
  await desktop.locator('#official-dormitory-search input').press('Enter');
  await desktop.waitForFunction(() => document.querySelectorAll('.official-visit-card').length === 1);
  await desktop.locator('.official-visit-card').click();
  await desktop.waitForSelector('.official-back');
  assert.match(new URL(desktop.url()).pathname, /^\/sude\/dormitories\/\d+$/);
  assert.match(await desktop.locator('.official-dormitory-hero').textContent(), /星光小屋/);
  await desktop.screenshot({ path: path.join(outputDir, 'official-dormitory-desktop.png'), fullPage: true });
  await desktop.locator('#roommate-system-btn').click();
  await desktop.waitForSelector('.roommate-card');
  await desktop.waitForSelector('.app-shell');
  await desktop.locator('#activity-system-btn').click();
  await desktop.waitForSelector('.activity-month-grid');
  assert.equal(new URL(desktop.url()).pathname, '/activities');
  assert.equal(await desktop.locator('.sidebar-brand strong').textContent(), '活动广场');
  assert.equal(await desktop.locator('.activity-filters > label').count(), 4);
  assert.equal(await desktop.locator('.activity-filters [name="location"]').count(), 0);
  assert.match(await desktop.locator('[data-activity-groups]').textContent(), /我的群组/);
  await desktop.locator('[data-activity-view="year"]').click();
  await desktop.waitForSelector('.activity-year-grid');
  assert.equal(await desktop.locator('.activity-mini-month').count(), 12);
  await desktop.locator('[data-activity-view="month"]').click();
  await desktop.waitForSelector('.activity-month-grid');
  assert.equal(await desktop.locator('[data-activity-date="2026-09-24"]').count(), 1);
  await desktop.locator('[data-activity-date="2026-09-24"]').click();
  await desktop.waitForSelector('.activity-day-layout');
  assert.equal(await desktop.locator('.activity-day-picker').count(), 7);
  assert.match(await desktop.locator('.activity-date-nav h2').textContent(), /9 月 24 日 · 星期四/);
  assert.match(await desktop.locator('.activity-time-group').first().textContent(), /18 个活动/);
  assert.match(await desktop.locator('[data-activity-expand]').first().textContent(), /展开其余 15 个/);
  await desktop.locator('[data-activity-view="week"]').click();
  await desktop.waitForSelector('.activity-week-cluster');
  assert.match(await desktop.locator('.activity-cluster-more').first().textContent(), /另有 18 个/);
  await desktop.screenshot({ path: path.join(outputDir, 'activity-plaza-desktop.png'), fullPage: true });
  await desktop.locator('.activity-week-cluster [data-activity-open]').first().click();
  await desktop.waitForSelector('.activity-detail-hero');
  assert.equal(await desktop.locator('.activity-detail-eyebrow').textContent(), 'CAMPUS EVENT');
  assert.match(await desktop.locator('.activity-registration-panel').textContent(), /当前报名.*还剩/s);
  assert.equal(await desktop.locator('[data-activity-copy-link]').count(), 1);
  await desktop.screenshot({ path: path.join(outputDir, 'activity-detail-desktop.png'), fullPage: true });
  await desktop.locator('[data-activity-template]').click();
  await desktop.waitForSelector('#activity-form');
  assert.match(await desktop.locator('.activity-template-note').textContent(), /正在以“.*”为模板/);
  await desktop.locator('[data-activity-clear-template]').click();
  await desktop.waitForFunction(() => !document.querySelector('.activity-template-note'));
  await desktop.locator('[data-activity-form-back]').click();
  await desktop.waitForSelector('.activity-week-cluster');
  await desktop.locator('[data-view="activities-groups"]').first().click();
  await desktop.waitForSelector('.activity-group-card');
  await desktop.locator('[data-create-activity-group]').click();
  await desktop.locator('#activity-group-form [name="name"]').fill('浏览器验收群组');
  await desktop.locator('#activity-group-form [name="memberIds"]').first().check();
  await desktop.locator('#activity-group-form .btn-primary').click();
  await desktop.waitForFunction(() => document.querySelector('.activity-group-list')?.textContent.includes('浏览器验收群组'));
  await desktop.locator('[data-view="activities-calendar"]').first().click();
  await desktop.locator('[data-activity-create]').click();
  await desktop.waitForSelector('#activity-form');
  assert.match(await desktop.locator('.activity-target-groups').textContent(), /浏览器验收群组.*我的群组/s);
  assert.equal(await desktop.locator('.activity-check-row').count(), 4);
  assert.equal(await desktop.locator('.activity-target-groups input').first().evaluate((input) => getComputedStyle(input).width), '16px');
  await desktop.screenshot({ path: path.join(outputDir, 'activity-form-desktop.png'), fullPage: true });
  await desktop.locator('#activity-form [name="title"]').fill('浏览器验收活动');
  await desktop.locator('#activity-form [name="location"]').fill('创新工坊 A201');
  await desktop.locator('#activity-form button[value="draft"]').click();
  await desktop.waitForSelector('.activity-detail-hero');
  assert.match(await desktop.locator('.activity-detail-hero').textContent(), /浏览器验收活动/);
  assert.match(await desktop.locator('.activity-detail-hero').textContent(), /草稿/);
  await desktop.locator('#roommate-system-btn').click();
  await desktop.waitForSelector('.roommate-card');
  assert.equal(await desktop.evaluate(async () => {
    try {
      await api('https://example.com/api/users');
      return false;
    } catch (error) {
      return error.message === '接口地址无效';
    }
  }), true);
  assert.equal(await desktop.locator('.roommate-card').count(), 15);
  assert.equal(await desktop.locator('[data-gender]').count(), 2);
  assert.match(await desktop.locator('[data-gender="FEMALE"]').getAttribute('class'), /active/);
  assert.equal(await desktop.locator('.sidebar-brand strong').textContent(), '合住');
  assert.equal(await desktop.locator('.roommate-card.gender-female').count(), 15);
  assert.equal(await desktop.locator('.roommate-card').first().evaluate((element) => getComputedStyle(element).backgroundColor), 'rgb(255, 246, 250)');
  assert.equal(await desktop.locator('#search-form input').getAttribute('placeholder'), '搜索姓名');
  assert.equal(await desktop.locator('.roommate-card .card-city').count(), 15);
  assert.equal(await desktop.locator('.roommate-card .card-note').count(), 15);
  assert.equal(await desktop.locator('.roommate-card .card-team').count(), 15);
  assert.equal(await desktop.locator('.roommate-card .card-metrics').count(), 0);
  const ownCard = desktop.locator('.roommate-card').filter({ hasText: '我的卡片' });
  assert.equal(await ownCard.count(), 1);
  assert.match(await ownCard.textContent(), /杭州/);
  assert.match(await ownCard.textContent(), /一缺三/);
  assert.match(await ownCard.textContent(), /我是一个开朗、直接/);
  assert.equal(await desktop.locator('#load-more-cards').count(), 1);
  await desktop.locator('#load-more-cards').click();
  await desktop.waitForFunction(() => document.querySelectorAll('.roommate-card').length === 16);
  const loadedCardIds = await desktop.locator('.roommate-card').evaluateAll((cards) => cards.map((card) => card.dataset.cardId));
  assert.equal(new Set(loadedCardIds).size, loadedCardIds.length);
  assert.equal(await desktop.locator('#load-more-cards').count(), 0);
  await desktop.locator('[data-gender="MALE"]').click();
  await desktop.waitForFunction(() => document.querySelector('[data-gender="MALE"]')?.classList.contains('active'));
  await desktop.locator('.roommate-card h3', { hasText: '陈遇' }).waitFor();
  assert.equal(await desktop.locator('.roommate-card').count(), 6);
  assert.equal(await desktop.locator('.roommate-card.gender-male').count(), 6);
  assert.equal(await desktop.locator('.roommate-card').first().evaluate((element) => getComputedStyle(element).backgroundColor), 'rgb(245, 249, 255)');
  assert.equal(await desktop.locator('.roommate-card').filter({ hasText: '我的卡片' }).count(), 0);
  await desktop.locator('[data-gender="FEMALE"]').click();
  await desktop.waitForFunction(() => document.querySelector('[data-gender="FEMALE"]')?.classList.contains('active'));
  await desktop.locator('.roommate-card h3', { hasText: '林夏' }).waitFor();
  assert.equal(await desktop.locator('.roommate-card').filter({ hasText: '我的卡片' }).count(), 1);
  await desktop.screenshot({ path: path.join(outputDir, 'student-desktop.png'), fullPage: true });

  await ownCard.click();
  await desktop.waitForSelector('.modal');
  assert.match(await desktop.locator('.modal').textContent(), /个人信息/);
  assert.match(await desktop.locator('.modal').textContent(), /生活节奏与空调/);
  assert.match(await desktop.locator('.modal').textContent(), /卫生与公共空间/);
  assert.match(await desktop.locator('.modal').textContent(), /游戏、声音与相处边界/);
  assert.match(await desktop.locator('.modal').textContent(), /用一句话介绍自己/);
  const detailText = await desktop.locator('.modal').textContent();
  assert.ok(detailText.indexOf('性格与兴趣') < detailText.indexOf('生活节奏与空调'));
  assert.equal((await desktop.locator('.modal .section-heading h2').allTextContents()).at(-1), '还想要对大家说');
  assert.match(await desktop.locator('.modal').textContent(), /院服尺码/);
  assert.equal(await desktop.locator('[data-edit-own]').count(), 1);
  await desktop.screenshot({ path: path.join(outputDir, 'card-detail.png'), fullPage: true });
  await desktop.locator('[data-edit-own]').click();

  await desktop.waitForSelector('#profile-form');
  assert.equal(await desktop.locator('#profile-form input:disabled').count(), 4);
  assert.equal(await desktop.locator('.size-guide').count(), 1);
  await desktop.locator('.size-guide summary').click();
  assert.equal(await desktop.locator('.size-table tbody tr').count(), 7);
  assert.equal(await desktop.locator('[name="clothing_size"] option').count(), 8);
  assert.equal(await desktop.locator('[name="personal_cleanliness"] option').count(), 4);
  assert.equal(await desktop.locator('[name="common_space_maintenance"] option').count(), 5);
  assert.equal(await desktop.locator('[name="one_sentence_intro"]').count(), 1);
  assert.equal(await desktop.locator('[data-unpublish]').count(), 0);
  assert.equal(await desktop.locator('#profile-form button[type="submit"]').textContent(), '更新卡片');
  assert.equal(await desktop.locator('[data-publish]').count(), 0);
  const personalitySection = desktop.locator('#profile-form .section').filter({ hasText: '性格与兴趣' });
  assert.equal(await personalitySection.locator('[name="self_acknowledged_shortcoming"]').count(), 1);
  assert.equal((await desktop.locator('#profile-form .section-heading h2').allTextContents()).at(-1), '还想要对大家说');
  assert.equal(await desktop.locator('#profile-form').getAttribute('data-overflow'), null);

  await desktop.locator('[data-view="settings"]').first().click();
  await desktop.waitForSelector('#password-form');
  assert.equal(await desktop.locator('#deactivate-btn').count(), 0);

  await desktop.locator('[data-view="dorm"]').first().click();
  await desktop.waitForSelector('.stage-banner');
  assert.match(await desktop.locator('.stage-banner').textContent(), /默认选宿舍轮次/);
  if (await desktop.locator('#create-dorm').count()) {
    await desktop.locator('#create-dorm').click();
    await desktop.waitForSelector('#create-dorm-form');
    assert.match(await desktop.locator('.modal').textContent(), /新建宿舍并加入/);
    assert.equal(await desktop.locator('#create-dorm-form [name="building"]').count(), 0);
    assert.equal(await desktop.locator('#create-dorm-form [name="roomNumber"]').count(), 0);
    assert.equal(await desktop.locator('#create-dorm-form [name="capacity"]').count(), 0);
    await desktop.locator('#create-dorm-form [name="name"]').fill('浏览器验收宿舍');
    await desktop.locator('#create-dorm-form .btn-primary').click();
    await desktop.waitForSelector('.dormitory-card.current');
  }
  assert.equal(await desktop.locator('.dormitory-card.current').count(), 1);
  assert.match(await desktop.locator('.dormitory-card').first().getAttribute('class'), /current/);
  assert.equal(await desktop.locator('.dormitory-card').count(), await desktop.locator('.dormitory-members').count());
  assert.match(await desktop.locator('.dormitory-card.current').textContent(), /林夏/);
  assert.equal(await desktop.locator('.dormitory-card.current [data-leave-dorm]').count(), 1);
  await desktop.screenshot({ path: path.join(outputDir, 'dormitory-desktop.png'), fullPage: true });

  await desktop.locator('[data-view="discover"]').first().click();
  await desktop.waitForSelector('.roommate-card');
  await desktop.locator('.roommate-card').filter({ hasText: '苏晴' }).click();
  assert.doesNotMatch(await desktop.locator('.modal').textContent(), /院服尺码/);
  await desktop.locator('[data-message]').click();
  await desktop.waitForSelector('#chat-messages');
  const chatLayout = await desktop.locator('.message-workspace').evaluate((workspace) => {
    const messages = workspace.querySelector('#chat-messages');
    const compose = workspace.querySelector('#message-form');
    for (let index = 0; index < 80; index += 1) {
      const message = document.createElement('div');
      message.className = `message ${index % 2 ? 'mine' : ''}`;
      message.textContent = `布局验收消息 ${index + 1}：${'较长内容'.repeat(12)}`;
      messages.append(message);
    }
    messages.scrollTop = messages.scrollHeight;
    const workspaceBox = workspace.getBoundingClientRect();
    const composeBox = compose.getBoundingClientRect();
    return {
      bodyFitsViewport: document.documentElement.scrollHeight <= window.innerHeight + 1,
      composeVisible: composeBox.top >= workspaceBox.top && composeBox.bottom <= workspaceBox.bottom + 1,
      messagesScrollable: messages.scrollHeight > messages.clientHeight && messages.scrollTop > 0,
      messagesOverflow: getComputedStyle(messages).overflowY,
    };
  });
  assert.equal(chatLayout.bodyFitsViewport, true);
  assert.equal(chatLayout.composeVisible, true);
  assert.equal(chatLayout.messagesScrollable, true);
  assert.equal(chatLayout.messagesOverflow, 'auto');
  const loggedOutSessionResponse = desktop.waitForResponse((response) => response.url() === `${baseUrl}/api/me`);
  await desktop.locator('#logout-btn').click();
  assert.equal((await loggedOutSessionResponse).status(), 401);
  await desktop.waitForSelector('.public-shell');
  assert.equal(await desktop.locator('#site-login').textContent(), '登录');
  assert.equal(await desktop.locator('#site-login').getAttribute('href'), '/login');
  await login(desktop, '2026002', 'Student123!');
  await desktop.locator('[data-view="messages"]').first().click();
  await desktop.waitForSelector('.message-workspace');
  assert.equal(await desktop.getByText('页面加载失败').count(), 0);

  const admin = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  admin.on('console', (message) => { if (message.type() === 'error' && !message.text().startsWith('Failed to load resource')) errors.push(`admin console: ${message.text()}`); });
  admin.on('pageerror', (error) => errors.push(`admin page: ${error.message}`));
  await login(admin, 'admin', 'Admin123!');
  await admin.waitForSelector('.stats-grid');
  assert.equal(await admin.locator('.stat').count(), 4);
  assert.match(await admin.locator('.panel').textContent(), /默认选宿舍轮次/);
  assert.equal(await admin.locator('[data-view="rounds"]').count() > 0, true);
  assert.equal(await admin.locator('[data-view="treehole-replies"]').count() > 0, true);
  assert.equal(await admin.locator('[data-view="treehole-content"]').count() > 0, true);
  assert.equal(await admin.locator('[data-view="official-dormitories"]').count() > 0, true);
  await admin.screenshot({ path: path.join(outputDir, 'admin-desktop.png'), fullPage: true });
  await admin.locator('[data-view="official-dormitories"]').first().click();
  await admin.waitForSelector('[data-admin-official-detail]');
  assert.equal(await admin.locator('#import-official-dormitories').count(), 1);
  assert.match(await admin.locator('#page-content').textContent(), /明德-101/);
  await admin.locator('[data-admin-official-detail]').first().click();
  await admin.waitForSelector('.official-admin-detail');
  assert.match(await admin.locator('.official-admin-detail').textContent(), /正式成员/);
  assert.equal(await admin.locator('[data-correct-official-members]').count(), 1);
  assert.equal(await admin.locator('[data-delete-official]').count(), 1);
  await admin.locator('.modal [data-close]').click();
  await admin.locator('#import-official-dormitories').click();
  await admin.waitForSelector('#official-dormitory-import');
  assert.match(await admin.locator('#official-dormitory-import').textContent(), /预检名单/);
  assert.match(await admin.locator('#official-dormitory-import input[type="file"]').getAttribute('accept'), /\.xlsx/);
  await admin.locator('#official-dormitory-import [data-cancel]').click();
  await admin.locator('[data-view="treehole-replies"]').first().click();
  await admin.waitForSelector('.treehole-admin-item');
  assert.match(await admin.locator('#page-content').textContent(), /第一次离家有些不适应/);
  await admin.locator('.treehole-admin-item').first().click();
  await admin.waitForSelector('.treehole-detail.admin');
  assert.equal(await admin.locator('#official-treehole-reply').count(), 1);
  assert.match(await admin.locator('.modal').textContent(), /林夏/);
  await admin.locator('.modal [data-close]').click();
  await admin.locator('[data-view="treehole-content"]').first().click();
  await admin.waitForSelector('#configure-treehole-grades');
  await admin.locator('#configure-treehole-grades').click();
  await admin.waitForSelector('#treehole-grade-form');
  assert.equal(await admin.locator('#treehole-grade-form input[name="gradeIds"]:checked').count(), 1);
  await admin.locator('#treehole-grade-form [data-cancel]').click();
  await admin.locator('[data-view="users"]').first().click();
  await admin.waitForSelector('#export-users');
  await admin.locator('#admin-user-search').fill('分页同学01');
  assert.equal(await admin.locator('[data-reset-password]').count(), 1);
  await admin.locator('[data-reset-password]').click();
  assert.match(await admin.locator('.modal').textContent(), /临时密码重置为当前登录标识/);
  assert.match(await admin.locator('.modal code').textContent(), /browser-page-01/);
  await admin.locator('#password-reset-reason').fill('浏览器验收密码重置');
  await admin.locator('.modal [data-confirm]').click();
  await admin.locator('.modal').waitFor({ state: 'detached' });
  await admin.waitForSelector('#export-users');
  const userDownloadPromise = admin.waitForEvent('download');
  await admin.locator('#export-users').click();
  const userDownload = await userDownloadPromise;
  assert.match(userDownload.suggestedFilename(), /^users-\d{4}-\d{2}-\d{2}\.xlsx$/);
  await admin.waitForSelector('#update-login-identifiers');
  await admin.locator('#update-login-identifiers').click();
  await admin.waitForSelector('#login-identifier-batch-form');
  assert.match(await admin.locator('#login-identifier-batch-form').textContent(), /整批校验并更新/);
  await admin.locator('#login-identifier-batch-form [data-cancel]').click();
  assert.equal(await admin.locator('[data-view="homepage"]').count(), 0);
  await admin.locator('[data-view="rounds"]').first().click();
  await admin.waitForSelector('#create-round');
  await admin.locator('#manage-selection-groups').click();
  await admin.waitForSelector('#create-selection-group');
  await admin.locator('#create-selection-group').click();
  await admin.waitForSelector('#selection-group-form');
  await admin.locator('#selection-group-form [name="name"]').fill('浏览器验收学生群组');
  await admin.locator('#selection-group-member-search').fill('沈知行');
  assert.equal(await admin.locator('#selection-group-candidates .candidate:visible').count(), 1);
  await admin.locator('#selection-group-member-search').fill('');
  await admin.locator('#selection-group-candidates .candidate', { hasText: '林夏' }).locator('input').check();
  await admin.locator('#selection-group-candidates .candidate', { hasText: '沈知行' }).locator('input').check();
  await admin.locator('#selection-group-form .modal-actions .btn-primary').click();
  const browserSelectionGroup = admin.locator('.selection-group-item', { hasText: '浏览器验收学生群组' });
  await browserSelectionGroup.waitFor();
  assert.equal(await browserSelectionGroup.locator('[data-export-selection-group]').count(), 0);
  await admin.locator('.modal [data-close]').click();
  await admin.locator('[data-view="cards"]').first().click();
  await admin.waitForSelector('#export-group-cards');
  await admin.locator('#export-group-cards').click();
  await admin.waitForSelector('#group-card-export-form');
  await admin.locator('#group-card-export-form .candidate', { hasText: '浏览器验收学生群组' }).locator('input').check();
  const groupCardDownloadPromise = admin.waitForEvent('download');
  await admin.locator('#group-card-export-form .btn-primary').click();
  const groupCardDownload = await groupCardDownloadPromise;
  assert.match(groupCardDownload.suggestedFilename(), /^selected-group-cards-\d{4}-\d{2}-\d{2}\.xlsx$/);
  await admin.locator('.modal').waitFor({ state: 'detached' });
  await admin.locator('[data-view="rounds"]').first().click();
  await admin.waitForSelector('#create-round');
  await admin.locator('#create-round').click();
  await admin.waitForSelector('#round-form');
  await admin.locator('#round-form [name="code"]').fill(`BROWSER_ROUND_${Date.now()}`);
  await admin.locator('#round-form [name="name"]').fill('浏览器验收轮次');
  await admin.locator('#round-form [data-person-search="round"]').fill('林夏');
  assert.equal(await admin.locator('#round-form [data-person-picker="round"] .candidate:visible').count(), 1);
  await admin.locator('#round-form [data-person-search="round"]').fill('');
  const roundSelectionGroupValue = await admin.locator('#round-form [data-person-group="round"] option', { hasText: '浏览器验收学生群组' }).getAttribute('value');
  await admin.locator('#round-form [data-person-group="round"]').selectOption(roundSelectionGroupValue);
  await admin.locator('#round-form [data-add-person-group="round"]').click();
  assert.equal(await admin.locator('#round-form [name="participantIds"]:checked').count(), 2);
  await admin.locator('#round-form .modal-actions .btn-primary').click();
  await admin.waitForSelector('.modal', { state: 'detached' });
  const browserRound = admin.locator('.round-admin-card', { hasText: '浏览器验收轮次' });
  await browserRound.waitFor();
  assert.equal(await browserRound.count(), 1);
  assert.equal(await browserRound.locator('[data-edit-round]').count(), 1);
  assert.equal(await browserRound.locator('[data-round-action="open"]').count(), 1);
  await admin.locator('[data-view="access"]').first().click();
  await admin.waitForSelector('#create-admin-group');
  assert.match(await admin.locator('#page-content').textContent(), /权限和年级范围必须由同一个组提供/);
  await admin.locator('#create-admin-group').click();
  await admin.locator('#create-group-form [name="code"]').fill(`BROWSER_${Date.now()}`);
  await admin.locator('#create-group-form [name="name"]').fill('浏览器验收管理员组');
  await admin.locator('#create-group-form [name="description"]').fill('验证组管理员工作台切换和动态菜单');
  await admin.locator('#create-group-form .btn-primary').click();
  await admin.waitForSelector('.access-card');
  await admin.locator('.access-card', { hasText: '浏览器验收管理员组' }).locator('[data-configure-group]').click();
  await admin.waitForSelector('#configure-group-form');
  const gradeInputId = await admin.locator('#configure-group-form label[for^="grade-"]', { hasText: /^2026级$/ }).getAttribute('for');
  for (const selector of [`#${gradeInputId}`, '#permission-USER_READ', '#permission-DORMITORY_READ']) {
    await admin.locator(selector).evaluate((element) => { element.checked = true; });
  }
  await admin.locator('#configure-group-form [data-person-search="admin-member"]').fill('沈知行');
  assert.equal(await admin.locator('#configure-group-form [data-person-picker="admin-member"] .candidate:visible').count(), 1);
  await admin.locator('#configure-group-form [data-person-search="admin-member"]').fill('');
  const adminSelectionGroupValue = await admin.locator('#configure-group-form [data-person-group="admin-member"] option', { hasText: '浏览器验收学生群组' }).getAttribute('value');
  await admin.locator('#configure-group-form [data-person-group="admin-member"]').selectOption(adminSelectionGroupValue);
  await admin.locator('#configure-group-form [data-add-person-group="admin-member"]').click();
  await admin.locator('#configure-group-form [name="reason"]').fill('浏览器权限验收');
  await admin.locator('#configure-group-form .btn-primary').click();
  await admin.waitForSelector('.modal', { state: 'detached' });
  const configuredGroup = admin.locator('.access-card', { hasText: '浏览器验收管理员组' });
  await configuredGroup.filter({ hasText: '沈知行' }).waitFor();
  assert.match(await configuredGroup.textContent(), /沈知行/);
  assert.match(await configuredGroup.textContent(), /2026级/);
  assert.match(await configuredGroup.textContent(), /查看用户/);
  await admin.locator('[data-view="groups"]').first().click();
  await admin.waitForSelector('#export-dormitories');
  assert.equal(await admin.locator('#admin-round-select').count(), 1);
  const downloadPromise = admin.waitForEvent('download');
  await admin.locator('#export-dormitories').click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /^dormitories-LEGACY_INITIAL-\d{4}-\d{2}-\d{2}\.xlsx$/);

  const groupAdmin = await browser.newPage({ viewport: { width: 1200, height: 800 }, deviceScaleFactor: 1 });
  groupAdmin.on('console', (message) => { if (message.type() === 'error' && !message.text().startsWith('Failed to load resource')) errors.push(`group admin console: ${message.text()}`); });
  groupAdmin.on('pageerror', (error) => errors.push(`group admin page: ${error.message}`));
  await login(groupAdmin, '2026005', 'Student123!');
  await groupAdmin.waitForSelector('.roommate-card');
  assert.equal(await groupAdmin.locator('#switch-mode').count(), 1);
  assert.match(await groupAdmin.locator('#switch-mode').textContent(), /进入管理工作台/);
  await groupAdmin.locator('#switch-mode').click();
  await groupAdmin.waitForSelector('.stats-grid');
  assert.equal(await groupAdmin.locator('[data-view="users"]').count() > 0, true);
  assert.equal(await groupAdmin.locator('[data-view="groups"]').count() > 0, true);
  assert.equal(await groupAdmin.locator('[data-view="rounds"]').count(), 0);
  assert.equal(await groupAdmin.locator('[data-view="cards"]').count(), 0);
  assert.equal(await groupAdmin.locator('[data-view="access"]').count(), 0);
  assert.equal(await groupAdmin.locator('[data-view="homepage"]').count(), 0);
  assert.match(await groupAdmin.locator('#switch-mode').textContent(), /返回学生端/);
  await groupAdmin.close();

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  mobile.on('console', (message) => { if (message.type() === 'error' && !message.text().startsWith('Failed to load resource')) errors.push(`mobile console: ${message.text()}`); });
  mobile.on('pageerror', (error) => errors.push(`mobile page: ${error.message}`));
  const mobileSessionResponse = mobile.waitForResponse((response) => response.url() === `${baseUrl}/api/me`);
  await mobile.goto(baseUrl, { waitUntil: 'domcontentloaded' });
  assert.equal((await mobileSessionResponse).status(), 401);
  await mobile.waitForSelector('.public-shell');
  assert.ok(await mobile.locator('.site-logo img').evaluate((image) => image.complete && image.naturalWidth > 0));
  assert.equal(await mobile.locator('.site-footer a').count(), 1);
  const homepageBodyWidth = await mobile.locator('body').evaluate((element) => element.scrollWidth);
  assert.ok(homepageBodyWidth <= 390, `mobile homepage overflows: ${homepageBodyWidth}px`);
  await mobile.screenshot({ path: path.join(outputDir, 'homepage-mobile.png'), fullPage: true });
  await login(mobile, '2026005', 'Student123!');
  await mobile.waitForSelector('.roommate-card');
  assert.equal(await mobile.locator('.mobile-nav').evaluate((element) => getComputedStyle(element).display), 'grid');
  const bodyWidth = await mobile.locator('body').evaluate((element) => element.scrollWidth);
  assert.ok(bodyWidth <= 390, `mobile body overflows: ${bodyWidth}px`);
  await mobile.locator('#activity-system-btn').click();
  await mobile.waitForSelector('.activity-day-layout');
  assert.equal(await mobile.locator('.mobile-nav button').count(), 2);
  assert.equal(await mobile.locator('.activity-day-picker').count(), 7);
  assert.equal(await mobile.locator('.activity-filters').isVisible(), false);
  await mobile.locator('[data-activity-toggle-filters]').click();
  await mobile.waitForFunction(() => document.querySelector('.activity-filters')?.classList.contains('open'));
  assert.equal(await mobile.locator('.activity-filters').isVisible(), true);
  assert.equal(await mobile.locator('[data-activity-toggle-filters]').getAttribute('aria-expanded'), 'true');
  await mobile.locator('[data-activity-toggle-filters]').click();
  await mobile.waitForFunction(() => !document.querySelector('.activity-filters')?.classList.contains('open'));
  await mobile.locator('[data-activity-view="month"]').click();
  await mobile.waitForSelector('.activity-month-grid');
  await mobile.locator('[data-activity-date="2026-09-24"]').click();
  await mobile.waitForSelector('.activity-time-group');
  assert.match(await mobile.locator('[data-activity-expand]').first().textContent(), /展开其余 15 个/);
  const activityBodyWidth = await mobile.locator('body').evaluate((element) => element.scrollWidth);
  assert.ok(activityBodyWidth <= 390, `mobile activity page overflows: ${activityBodyWidth}px`);
  await mobile.screenshot({ path: path.join(outputDir, 'activity-plaza-mobile.png'), fullPage: true });
  await mobile.locator('#roommate-system-btn').click();
  await mobile.waitForSelector('.roommate-card');
  await mobile.locator('#treehole-system-btn').click();
  await mobile.waitForSelector('.treehole-card');
  const treeholeBodyWidth = await mobile.locator('body').evaluate((element) => element.scrollWidth);
  assert.ok(treeholeBodyWidth <= 390, `mobile treehole page overflows: ${treeholeBodyWidth}px`);
  await mobile.screenshot({ path: path.join(outputDir, 'treehole-mobile.png'), fullPage: true });
  await mobile.locator('#official-dormitory-system-btn').click();
  await mobile.waitForSelector('.official-dormitory-hero');
  assert.match(await mobile.locator('#page-content').textContent(), /还没有正式宿舍/);
  await mobile.locator('[data-view="official-visit"]').last().click();
  await mobile.waitForSelector('.official-visit-grid');
  const officialDormitoryBodyWidth = await mobile.locator('body').evaluate((element) => element.scrollWidth);
  assert.ok(officialDormitoryBodyWidth <= 390, `mobile official dormitory page overflows: ${officialDormitoryBodyWidth}px`);
  await mobile.screenshot({ path: path.join(outputDir, 'official-dormitory-mobile.png'), fullPage: true });
  await mobile.locator('#roommate-system-btn').click();
  await mobile.waitForSelector('.roommate-card');
  await mobile.locator('.roommate-card').first().click();
  const cardModal = mobile.locator('.modal');
  const closeCardButton = cardModal.locator('[data-close]');
  await closeCardButton.waitFor();
  const closeCardButtonBox = await closeCardButton.boundingBox();
  assert.ok(closeCardButtonBox && closeCardButtonBox.x >= 0 && closeCardButtonBox.y >= 0);
  assert.ok(closeCardButtonBox.x + closeCardButtonBox.width <= 390);
  assert.ok(closeCardButtonBox.y + closeCardButtonBox.height <= 844);
  await closeCardButton.click();
  await assert.rejects(() => cardModal.waitFor({ state: 'visible', timeout: 250 }));
  await mobile.locator('.roommate-card').nth(1).click();
  await mobile.locator('[data-message]').click();
  await mobile.locator('[data-chat-back]').waitFor();
  await mobile.locator('[data-chat-back]').click();
  await mobile.waitForFunction(() => !document.querySelector('.chat-head'));
  assert.equal(await mobile.locator('.conversation-list').isVisible(), true);
  assert.equal(await mobile.locator('.chat-head').count(), 0);
  await mobile.screenshot({ path: path.join(outputDir, 'student-mobile.png'), fullPage: true });
  await mobile.locator('[data-view="dorm"]').last().click();
  await mobile.waitForSelector('.stage-banner');
  const dormBodyWidth = await mobile.locator('body').evaluate((element) => element.scrollWidth);
  assert.ok(dormBodyWidth <= 390, `mobile dormitory page overflows: ${dormBodyWidth}px`);
  await mobile.screenshot({ path: path.join(outputDir, 'dormitory-mobile.png'), fullPage: true });

  await browser.close();
  browser = null;
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: static homepage, activity plaza, cards, permissions, dormitories, official dormitories, export, and mobile layouts.');
})().catch(async (error) => {
  if (browser) await browser.close();
  console.error(error);
  process.exitCode = 1;
});
